### ISSUE TITLE
[usage question] how can I parse a CWL file to the cwlavro model

### ISSUE THREAD

**Issue by pr80ik** [common-workflow-language/cwlavro#16]
I would like to parse CWL file into java model classes. I'm using cwl-avro (version: 2.0.4.2) as the model classes. How can I parse the cwl file so that I get back an instance of `io.cwl.avro.Workflow.Workflow` class

[reference](https://www.biostars.org/p/354853/)

**Comment by pr80ik** [comment]
@denis-yuen

**Comment by denis-yuen** [comment]
@pr80ik 
Hi,
There is a test that demonstrates how to parse a file to get back a CommandLineTool https://github.com/common-workflow-language/cwlavro/blob/master/cwlavro-tools/src/test/java/AbstractClientTest.java#L162

Getting back a Workflow is essentially the same, although there isn't a test example of it in this repo. 
https://github.com/ga4gh/dockstore/blob/8f4a0cf40214021fbc063e252dde36257b0bcc67/dockstore-webservice/src/main/java/io/dockstore/webservice/languages/CWLHandler.java#L237

Hope that helps!
